#!/usr/bin/env bash
# Custom script to generate a welcome page

echo '
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Nothing!</title>
</head>
<body>
    <h1>Hello World!</h1>
    <img src="~/Welcome.jpg" alt="Starry Space" />
</body>
</html>
' | sudo tee /custom_welcome.html > /dev/null

sudo sed -i s"/index hello.html/index custom_welcome.html/" /etc/nginx/sites-available/default
sudo service nginx restart
